### ISSUE TITLE
[Meta-issue] Optimize python/add_data.sh

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/opendrr-api#76]
Goals include:

* Reduce build time
* Reduce disk usage
* Increase robustness / resilience (e.g. recovering from curl download interruption)
* ... (to be continued)

- [ ] Preliminary re-organization (PR #68)
    - [x] Add header comment, make comments easier to read, and similar trivial/pedantic changes
    - [ ] Use `jq` to simply JSON parsing (see https://cameronnokes.com/blog/working-with-json-in-bash-using-jq/)
    - [ ] Move repetitive calls into functions (first round):
        - [x] run_psql()
        - [x] run_ogr2ogr()
        - [ ] fetch_csv() (for CSV files hosted on GitHub, esp. LFS files)
    - [ ] Add `apt-get install -y jq` to python/Dockefile

- [ ] add_data.sh: curl commands (make download more fault tolerant) (Issue #66)

- [ ] add_data.sh - flexible data loading (OpenDRR/model-factory#53)

 - [ ] Shellcheck
    - [ ] Add GitHub workflow to run ShellCheck GitHub action, see https://github.com/marketplace/actions/shellcheck
    - [ ] Fix ShellCheck errors and warnings

- [ ] Move repetitive calls into functions (second round)
    - [ ] fetch_dir() (for listings (directories) hosted on GitHub)
    - [ ] run_git_clone()  (?)

- [ ] Benchmark and profiling

### Future tasks (that have yet to be turned into GitHub issues):

* Use of e.g. `/usr/bin/time -v` for profiling
* `docker-compose logs -f -t` provides log with timestamp
* Some kind of DEBUG variable?  e.g. Make the psql flag `-a` or `--echo-all` optional unless in DEBUG mode for a more concise log.
* Add option to delete downloaded *.gpkg and *.csv files as soon as they have been imported to save space
* etc.

Maybe in Round 2 of refactoring?  Or this round?  Need to discuss with Drew first:

- Leave the model-factory/scripts/* files where they are instead of copying them?
- Use e.g. _build and _data directories to separate our code from downloaded data and temporary build files?

Random ideas, questions, etc.

- Make add_data.sh capable of being run over and over again ("incremental build", build stamp, etc.)
    - ogr2ogr, if run repeatedly with the same data: `-append`, `-update`, or `-overwrite`
- Use Backblaze S2 for large file storage for speed and reduced cost?  https://nickb.dev/blog/backblaze-b2-as-a-cheaper-alternative-to-githubs-git-lfs
    - GitHub data packs: Storage for $0.1/GB/month storage, Download for $0.1/GB download (TODO: verify)
    - Amazon S3: TODO
    - Backblaze S2: Storage for $0.005/GB/month storage; Download for $0.01/GB
- Use eatmydata with PostgreSQL for speed

**Comment by anthonyfok** [comment]
Benchmark (in progress, to be edited)

| Duration  | Command |
| ------------- | ------------- |
| 2s | `git clone https://github.com/OpenDRR/model-factory.git --depth 1` |
|  4m58s | `git clone https://github.com/OpenDRR/boundaries.git --depth 1`  |
| 3m08 | ogr2ogr runs on the 9 .gpkg files from OpenDRR/boundaries |
